version: '3.8'

services:
  web:
    build:
      context: .
      target: build
    image: shop_dec_6:latest
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      BUNDLE_DEPLOYMENT: '1'
      BUNDLE_PATH: '/usr/local/bundle'
      BUNDLE_WITHOUT: 'development'
    entrypoint: ["/rails/bin/docker-entrypoint"]
